VIA_ENABLE = yes
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = no
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite

IDLE_TIMEOUT_ENABLE = yes

ENCODER_DEFAULTACTIONS_ENABLE = no
COLEMAK_LAYER_ENABLE = no  #Enable Colemak layer / set to no to disable
TD_LSFT_CAPSLOCK_ENABLE = no
STARTUP_NUMLOCK_ON = no
INVERT_NUMLOCK_INDICATOR = no
